require 'pry'

QUESTIONS = [
"Tell me a little about yourself.",
"What are your strengths?",
"What are your weaknesses?",
"Where do you see yourself in five years?",
"What do you know about our company?",
"Are you good at dealing with change?",
"Do you work well under pressure?",
"I'll run it by as many people I as I can, be they managers, coworkers, or family members.",
"What's the last book you read?",
"Tell me, in as few words as possible, how you manage ambiguity",
"Tell me, in as few words as possible, how you manage stress in the workplace?",
"If you were an animal, what would you be?",
"What development tools have you used?",
"What languages have you programmed in?",
"What source control tools have you used?",
"What are your technical certifications?",
"How did your education help prepare you for this job?",
"How would you rate your key competencies for this job?",
"What are your IT strengths and weaknesses?",
"Tell me about the most recent project you worked on. What were your responsibilities?",
"From the description of this position what do you think you will be doing on a day-to-day basis?",
"What challenges do you think you might expect in this job if you were hired?",
"How important is it to work directly with your business users?",
"What elements are necessary for a successful team and why?",
"Tell me about the project you are most proud of, and what your contribution was.",
"Describe your production deployment process.",
"Give an example of where you have applied your technical knowledge in a practical way.",
"How did you manage source control?",
"What did you do to ensure quality in your deliverables?",
"What percentage of your time do you spend unit testing?",
"What do you expect in the solution documents you are provided?",
"Describe a time when you were able to improve upon the design that was originally suggested.",
"How much reuse do you get out of the code that you develop, and how?",
"Which do you prefer; service oriented or batch oriented solutions?",
"When is the last time you downloaded a utility from the internet to make your work more productive, and what was it?",
"What have you done to ensure consistency across unit, quality, and production environments?",
"Describe the elements of an in tier architecture and their appropriate use.",
"Compare and contrast REST and SOAP web services.",
"Define authentication and authorization and the tools that are used to support them in enterprise deployments.",
"What is ETL and when should it be used?",
"You have been asked to research a new business tool. You have come across two solutions. One is an on-premises solution, the other is cloud-based. Assuming they are functionally equivalent, would you recommend one over the other, and why?",
"What do you do to ensure you provide accurate project estimates?",
"What technical websites do you follow?",
"Have you used Visual Studio?",
"Have you used Eclipse?",
"What is a SAN, and how is it used?",
"What is clustering, and describe its use.",
"What is the role of the DMZ in network architecture?",
"How do you enforce relational integrity in database design?",
"When is it appropriate to denormalize database design?",
"What is the difference between OLAP and OLTP? When is each used?",
"You have learned that a business unit is managing a major component of the business using Excel spreadsheets and Access databases. What risks does this present, and what would you recommend be done to mitigate those risks?",
"What automated-build tools or processes have you used?",
"What is the role of continuous integration systems in the automated-build process?",
"Describe the difference between optimistic and pessimistic locking.",
"In databases, what is the difference between a delete statement and a truncate statement?",
"What are transaction logs, and how are they used?",
"What are the most important database performance metrics, and how do you monitor them?",
"What is the role of SNMP?",
"What is a cross site scripting attack, and how do you defend against it?",
"In network security, what is a honey pot, and why is it used?",
"What is a Style Sheet?",
"How can I include comments in my Style Sheet?",
"How do you clear a floated element?",
"How do I center block-elements with CSS1?",
"What is a sprite? How is it applied using CSS? What is the benefit?",
"Why was the decision made to make padding apply outside of the width of a 'box' rather than inside, which would seem to make more sense?",
"Which browsers support CSS?",
"Name three ways to define a color in HTML",
"What are the advantages/disadvantages of the various style methods?",
"Explain the difference between visibility:hidden; and display:none.",
"Tell me about a challenge you've faced, and how you overcame it",
"What do you like most about programming",
"How did you get into programming?",
]

def ask_question
  %x( say #{QUESTIONS.sample}) 
end

binding.pry
