require 'pry'

QUESTIONS = [
"Tell me a little about yourself.",
"What are your strengths?",
"What are your weaknesses?" ,
"Where do you see yourself in five years?",
"What do you know about our company?",
"Are you good at dealing with change?",
"Do you work well under pressure?",
"How do you make important decisions?",
"What's the last book you read?",
"Tell me, in as few words as possible, how you manage ambiguity",
"Tell me, in as few words as possible, how you manage stress in the workplace?",
"If you were an animal, what would you be?",
"What development tools have you used?",
"What languages have you programmed in?",
"What source control tools have you used?",
"What are your technical certifications?",
"How did your education help prepare you for this job?",
"How would you rate your key competencies for this job?",
"What are your IT strengths and weaknesses?",
"Tell me about the most recent project you worked on. What were your responsibilities?",
"From the description of this position what do you think you will be doing on a day-to-day basis?",
"What challenges do you think you might expect in this job if you were hired?",
"How important is it to work directly with your business users?",
"What elements are necessary for a successful team and why?",
"Tell me about the project you are most proud of, and what your contribution was.",
"Describe your production deployment process.",
"Give an example of where you have applied your technical knowledge in a practical way.",
"What percentage of your time do you spend unit testing?",
"What do you expect in the solution documents you are provided?",
"When is the last time you downloaded a utility from the internet to make your work more productive, and what was it?",
"Compare and contrast REST and SOAP web services.",
"Define authentication and authorization and the tools that are used to support them in enterprise deployments.",
"What is ETL and when should it be used?",
"You have been asked to research a new business tool. You have come across two solutions. One is an on-premises solution, the other is cloud-based. Assuming they are functionally equivalent, would you recommend one over the other, and why?",
"What technical websites do you follow?",
"What is clustering, and describe its use.",
"What is the role of the DMZ in network architecture?",
"In databases, what is the difference between a delete statement and a truncate statement?",
"What are transaction log, and how are they used?",
"In network security, what is a honey pot, and why is it used?",
"What is a Style Sheet?",
"How can I include comments in my Style Sheet?",
"How do you clear a floated element?",
"What is a sprite? How is it applied using CSS? What is the benefit?",
"Which browsers support CSS?",
"Name three ways to define a color in HTML",
"Tell me about a challenge you've faced, and how you overcame it",
"What do you like most about programming",
"How did you get into programming?",
"What's your worst habit",
]

def ask_question
  %x( say #{QUESTIONS.sample}) 
end

